### ISSUE TITLE
$ico_menu being overritten

### ISSUE THREAD

**Issue by J-Setzer** [myappgini/lteadmin#1]
Hi great work, so far!

Setting `$ico_menu` in `header_lte_leftSideMenu.php` overwrites any setting in `config_lte.php`.
Lines `34` to `42` of `header_lte_leftSideMenu.php` should be removed, I guess.

```php
// $ico_menu = '{
//     "Documenti":"fa fa-table",
//     "Catalogo":"fa fa-gift",
//     "Prima Nota":"fa fa-pencil-square-o",
//     "Anagrafiche":"fa fa-cog",
//     "Altro":"fa fa-plus",
//     "hiddens":"fa fa-eye-slash",
//     "Stammdaten": "fa fa-plus"
// }';
```
Thanks for sharing!
Jan

**Comment by landinialejandro** [comment]
fix it! thanks!
