### ISSUE TITLE
How to keep current toggle-state between pages

### ISSUE THREAD

**Issue by J-Setzer** [myappgini/lteadmin#2]
Hi, 

I suggest adding the following javascript code at the end of footer **to keep the toggle-state between pages**:

```js
<script>
  if (Boolean(sessionStorage.getItem("sidebar-toggle-collapsed"))) {
    $j("body").addClass('sidebar-collapse')
  }

  $j('.sidebar-toggle').click(function() {
    event.preventDefault();
    if (Boolean(sessionStorage.getItem("sidebar-toggle-collapsed"))) {
      sessionStorage.setItem("sidebar-toggle-collapsed", "");
    } else {
      sessionStorage.setItem("sidebar-toggle-collapsed", "1");
    }
  });
</script>
```

I've taken the solution from here:
https://github.com/ColorlibHQ/AdminLTE/issues/1240

Regards,
Jan

**Comment by landinialejandro** [comment]
hi Jan! wold do you like me to add you as contributor to this project?

**Comment by landinialejandro** [comment]
in the last version i was make this changue, check appginiAdminlte.js inside dit/js folder.
I await your comments to close this topic.
thanks

**Comment by landinialejandro** [comment]
fixed ir
